- tab:
    id: id_30
    text: tab1
    rows:
      - gridrow:
          - p:
              id:
          - p:
              id:
          - h2:
              id: id_7
              text: header2
              mutable: true
          - p:
              id:
          - p:
              id:
      - gridrow:
          - dropdown:
              id: id_1
              defaultind: 1
              items:
                #- uno
                #- due
                #- tre
          - button:
              id: id_2
              text: press
      - gridrow:
          - date:
              id: id_30
- tab:
    id: id_31
    text: tab2
    rows:
      - gridrow:
          - form:
              id: id_3
              text: submit
          - slider:
              id: id_4
              minmaxini:
                - 10
                - 100
                - 30
          - label:
              id: id_6
              text: "30"
              mutable: true
      - gridrow:
          - textarea:
              id: id_5
              text: ">>>"
              lines: 10
- tab:
    id: id200
    text: tab3
    rows:
        - gridrow:
          - p:
              id:
          - button:
              id: id_41
              text: draw
          - p:
              id: id_42
        - gridrow:
          - p:
              id:
          - image:
                id: id_46
          - p:
              id:


- tab:
    id: id201
    text: tab 4
    rows:
        - gridrow:
          - plot:
                id: id_47
          - plot:
                id: id_48
          - plot:
                id: id_49
          - plot:
                id: id_50

